env:
  CIRRUS_CLONE_DEPTH: 1

freebsd_14_task:
  freebsd_instance:
    image_family: freebsd-14-3
  install_script:
    - pkg install -y autoconf automake
    - ./package/setup-configure
  basic_script: &basic
    - "[ -f Makefile ] && gmake distclean"
    - ./configure || { cat config.log; exit 1; }
    - gmake
    - gmake test
  uds_script: &uds
    - "[ -f Makefile ] && gmake distclean"
    - ./configure --with-trust-uds-cred --with-uds || { cat config.log; exit 1; }
    - gmake
    - gmake test
  pam_ssl_script: &pamssl
    - "[ -f Makefile ] && gmake distclean"
    - ./configure --with-pam --with-openssl || { cat config.log; exit 1; }
    - gmake
    - gmake test
  gssapi_script: &gssapi
    - "[ -f Makefile ] && gmake distclean"
    - ./configure --with-gssapi || { cat config.log; exit 1; }
    - gmake
    - gmake test

linux_gcc_task:
  container:
    image: gcc:latest
  install_script:
    - ./package/setup-configure
  basic_script: *basic
  uds_script: *uds
  pam_ssl_script: *pamssl
