#!/bin/sh

set -e

cp package/config.guess .
cp package/config.sub .

# We set lang to avoid this with the gcc docker image on cirrus:
# 
#   ./package/setup-configure
#   perl: warning: Setting locale failed.
#   perl: warning: Please check that your locale settings:
#   	LANGUAGE = (unset),
#   	LC_ALL = (unset),
#   	LANG = "en_US.UTF-8"
#       are supported and installed on your system.

LANG=C autoreconf
